#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function

SITES = [['Synalp site', 'http://talc1.loria.fr/synalp//'],
         ['LOGE', 'http://loge.github.io/'],
         ['Hanskalabs', 'http://www.hanskalabs.net/'],
         ['Deploshark', 'http://www.pampati.com.ar/'],
         ['Gotham Blog', 'http://gothamblog.nemocorp.info/'],
         ['lkhj', 'https://f.lkjh.nl/'],
         ["Lan, Yi-Tin's Notes", 'http://lanyitin.tw/'],
         ['AG Technik Niedersachsen', 'http://datenbunker.biz/'],
         ['Software', 'http://mattdietz.net/'],
         ['thewolfeway', 'http://thewolfeway.net/'],
         ['Javier Cordero', 'http://corderomartinez.es/'],
         ['LaNAIS de RMS', 'http://www.lanais.famaf.unc.edu.ar/'],
         ['bits and bytes', 'http://rmrn.net/'],
         ['Domink Schacht', 'http://www.dominik-schacht.com/'],
         ['FOR FUTURE REFERENCE...', 'http://brunettoziosi.eu/'],
         ['Deni Bertović', 'http://denibertovic.com/'],
         ['Humitos', 'http://blog.mkaufmann.com.ar/'],
         ['staalkemade.net', 'http://staalkemade.nl/'],
         ['Nicola Gramola', 'http://gramola.net/'],
         ['麦客园', 'http://mc.basebb.com/'],
         ['David Beath', 'http://www.davidbeath.com/'],
         ['Content Musings', 'http://contentmusings.ddevnet.net/'],
         ['bluehat.us', 'http://bluehat.us/'],
         ['U. Maine Hydrogeology', 'http://hydro16.geology.um.maine.edu/'],
         ['a mingled cup', 'http://dave.dkjones.org/'],
         ["howlanderson's blog", 'http://howlanderson.bitbucket.org/'],
         ['AVB', 'http://avb.statusbar.com/'],
         ['Consciousness Riven', 'http://halosghost.github.io/'],
         ['@mattoc', 'http://mattoc.com/'],
         ['Big Data and Public Health 2013', 'http://emap.fgv.br/BDPH2013/'],
         ['小小驿站', 'http://iefan.github.io/'],
         ['Dgplug Summer Training 2013', 'http://dgplug.org/summertraining/2013/'],
         ['Crowdfunded Free Software', 'http://cffsw.modernthings.org/'],
         ['Stefan Antoni I/O', 'http://blog.antoni.io/'],
         ["chensy's blog", 'http://chensy0203.github.io/'],
         ['Bruno Carlin', 'http://bcarlin.net/index.html'],
         ['Dillahunty Family Web', 'http://www.dillahunty.com/'],
         ['Tales of a Python coder [...]', 'http://people.ksp.sk/~johnny64/blog/'],
         ['Pleasant Programmer', 'http://thatsmydoing.github.io/'],
         ['Bert McDowell', 'http://bertmcdowell.com/'],
         ['frangor.info', 'http://frangor.info/'],
         ['Unprivileged User', 'http://teythoon.cryptobitch.de/'],
         ['VocalBit', 'http://vocalbit.com/'],
         ['Planet Pi', 'http://planetpi.org/'],
         ['Zato Blog', 'https://zato.io/blog/'],
         ["Astynax's Blog", 'http://astynax.github.io/'],
         ['X421', 'http://x421.de/'],
         ['This Week in Fedora', 'http://ambre.pingoured.fr/thisweekinfedora/'],
         ['What a n00b!', 'http://www.whatan00b.com/'],
         ['JC Martin', 'http://www.jcmartin.org/'],
         ["Amr Elroumy's Blog", 'http://amrelroumy.github.io/'],
         ["Dhruv Baldawa's Web Log", 'http://www.dhruvb.com/blog/'],
         ['M-x and other things...', 'http://ivoarch.github.io/'],
         ['Curious Efficiency', 'http://www.curiousefficiency.org/'],
         ["cuerty's", 'http://blog.cuerty.com/'],
         ['Ocupaciones Raras', 'http://ocupacionesraras.com.ar/'],
         ["Jeremy's Pages", 'http://jerenept.github.io/'],
         ['kevinzhang.org', 'http://kevinzhang.org/'],
         ["Dr4K4n's blog", 'http://www.twimbee.de/'],
         ['DDEVnet.net', 'http://ddevnet.net/'],
         ['Ayudemos a Fiama', 'http://ayudarafiama.com.ar/'],
         ['Nathalie & Guilhem', 'http://nathguil.free.fr/'],
         ['Progstasis', 'http://progstasis.com/'],
         ['شاهینیسم', 'http://shahinism.github.io/'],
         ['Tecky old GI+', 'http://www.cjbarnes18.me.uk/'],
         ['AlianStudio.info', 'http://alianstudio.info/'],
         ['notfoss', 'http://notfoss.com/'],
         ['hbprotoss的博客', 'http://hbprotoss.github.io/'],
         ['sahiga', 'http://stephaniehiga.com/'],
         ['Perlitas Matemáticas', 'http://mate.dm.uba.ar/~pdenapo/blog/'],
         ['Gavim M. Roy', 'http://gavinroy.com/'],
         ["tommyvn's blog", 'http://tomvn.com/'],
         ['/Home', 'http://slashome.zapto.org/'],
         ['meldh', 'http://meldh.com/'],
         ['synesthesiam', 'http://synesthesiam.github.io/'],
         ['Troy Story', 'http://blog.tomanator.com/'],
         ['MEDIACORE', 'http://mediacorecommunity.org/blog/'],
         ["vaa's personal page", 'http://vaa.sk/'],
         ['Dígame licenciado', 'http://www.kirkner.com.ar/'],
         ['PronexDengue', 'http://claudia-codeco.github.io/pronex/'],
         ['Chaos Affinity Werx', 'http://chaosaffinitywerx.com/'],
         ["chris' random ramblings", 'http://atlee.ca/blog/'],
         ['Ultimate!', 'http://ultimatesport.in/'],
         ['Stochastic Scholastics', 'http://stochastics.komodo.re/'],
         ['Planet Python Deutschland', 'http://planet-python.de/'],
         ['eduardocollado.com', 'http://eduardocollado.com/'],
         ['Блог Андрея Смирнова', 'http://www.smira.ru/'],
         ['cowlicks', 'http://cwl.cx/'],
         ['digitalbrains.com', 'http://digitalbrains.com/'],
         ['Cases', 'http://blog.fizyk.net.pl/'],
         ['Bl4ckB1rd', 'http://www.bl4ckb1rd.com.ar/'],
         ['Infraconsulting', 'http://www.infraconsulting.it/'],
         ['Owl Motion', 'http://www.owlmotion.com/'],
         ['ventolin.org', 'http://blog.ventolin.org/'],
         ['serialized.net', 'http://serialized.net/'],
         ['Simeon Visser', 'http://simeonvisser.com/'],
         ['Untested things never work', 'http://www.markus-ullmann.de/'],
         ['Atokgeekz', 'http://atokgeekz.comyr.com/'],
         ['Blog Maya', 'http://diegoduncan21.github.com/'],
         ['Startafire', 'http://blog.nerdno.de/'],
         ['Tamedbeast', 'http://www.tamedbeast.de/'],
         ["Perseo's Blog", 'http://www.perseosblog.com/'],
         ['Pejibaye Blog', 'http://kaeruct.github.com/'],
         ['Corleonis', 'http://swind.code-life.info/'],
         ['Kill -9', 'http://www.cs.put.poznan.pl/ddwornikowski/blog/'],
         ['Tinkering with stuff', 'http://tinkeringwithstuff.com/'],
         ["fredy's blog", 'http://adamkalis.github.com/'],
         ['Bworth Says', 'http://blog.bworth.com/bworthsays/'],
         ['Planeta Hispano', 'http://planethispano.com/'],
         ['I me mine', 'http://sergiusens.github.com/'],
         ['CodeSpeak', 'http://codespeak.cc/'],
         ['优格猫', 'http://yogurtcat.com/'],
         ['Wordspeak', 'http://wordspeak.org/'],
         ['shisaa.jp', 'http://shisaa.jp/'],
         ['Fatiando a Terra', 'http://fatiando.org/'],
         ['Ink & incapability', 'http://blog.duncancreek.net/'],
         ['男单618', 'http://www.ai7.org/blog/'],
         ["Kw’s Blog", 'http://kwpolska.tk/'],
         ['The journey that counts', 'http://blog.journeythatcounts.nl/'],
         ['Unlogic', 'http://unlogic.co.uk/'],
         ['APU CSFC', 'http://apu-csfc.github.com/'],
         ["Marcos Alcazar's Blog", 'http://blog.marcosalcazar.com.ar/'],
         ['@rtnpro', 'http://www.rtnpro.com/'],
         ['Intellectual Web', 'http://sayanchowdhury.dgplug.org/'],
         ['The Eyegrade Blog', 'http://www.it.uc3m.es/jaf/eyegrade/blog/'],
         ['Tryton', 'http://www.tryton.org/'],
         ['Null Cortex', 'http://nullcortex.com/'],
         ['Secret Weblog', 'http://blog.startifact.com/'],
         ['①＝③', 'http://www.oneis3.com/'],
         ['Frogblog', 'http://blog.vfrog.es/'],
         ['Roman Imankulov', 'http://www.imankulov.name/'],
         ["Rail's Blog", 'http://rail.merail.ca/'],
         ['uwe.ambloggen.de', 'http://uwe.ambloggen.de/'],
         ["Rok's occasional blog", 'http://rok.mocnik.me/'],
         ['José Matos Home Page', 'http://webapps.fep.up.pt/jamatos/'],
         ["Teddy's World", 'http://tedyin.com/'],
         ['Carlos Enrique Rodriguez', 'http://cerodriguez.com.ar/'],
         ['Living the Appian Way', 'http://appianway.altervista.org/'],
         ['FOSS and life', 'http://kushaldas.in/'],
         ['QTPC', 'http://qtpc.com.ar/'],
         ['flexion.org', 'http://flexion.org/'],
         ["Mariano Guerra's Log", 'http://www.marianoguerra.org/'],
         ["Damian's blog", 'http://www.damian.oquanta.info/'],
         ['Rounder Wheels', 'http://blog.schettino72.net/'],
         ['Patrick Wildt', 'http://www.patrick-wildt.de/blog/'],
         ['Gekwetter', 'http://barometz.name/'],
         ['Ivan Teoh', 'http://www.ivanteoh.com/'],
         ['Procoders', 'http://www.procoders.net/'],
         ['Felipe Lerena', 'http://www.felipelerena.com.ar/'],
         ['Juan Rodriguez Monti', 'http://www.juanrodriguezmonti.com.ar/'],
         ['Nuitka Home and Blog of Kay Hayen', 'http://nuitka.net/'],
         ['Brian Curtin', 'http://blog.briancurtin.com/'],
         ['tin_nqn', 'http://mgaitan.github.com/'],
         ['Majority of One', 'http://majorityofone.co.il/stories/intro.html/'],
         ['El Jose Blog', 'http://jose.rebeldes.org.ar/'],
         ['Ninjas, Pythones y Samurais!', 'http://www.edvm.com.ar/'],
         ['madumlao', 'http://madumlao.is-a-geek.org/blog/'],
         ['Planeta PyAr', 'http://planeta.python.org.ar/'],
         ["Thorsten's Blog", 'http://blog.aero2k.de/']]

SITES.sort()
SITES = [['Lateral Opinion', 'http://ralsina.me/weblog/'],
         ['Nikola', 'http://getnikola.com/'],
         ['Rst2pdf', 'http://rst2pdf.ralsina.com.ar']] + SITES

import app

PAGES = []

print('{0} sites to migrate.\n'.format(len(SITES)))

print('Stage 1 of 3: ', end='')

for i in SITES:
    PAGES.append(app.Page(i[0], i[1], 'unknown', '', '', False, visible=True))
    print('.', end='')

print('\nStage 2 of 3: ', end='')

for i in PAGES:
    app.db.session.add(i)
    print('.', end='')

print('\nStage 2 of 3: ', end='')
app.db.session.commit()
print('OK')
