# Generated by Django 2.2.1 on 2019-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, unique=True, verbose_name='URL')),
                ('exact', models.BooleanField(default=False, verbose_name='Exact match')),
            ],
            options={
                'verbose_name': 'blacklisted URL',
                'verbose_name_plural': 'blacklisted URLs',
            },
        ),
    ]
